"""initial migration

Revision ID: 78a1a03a5d32
Revises: 
Create Date: 2020-04-01 17:39:21.112375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a1a03a5d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_bluetooth_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_bluetooth_id', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspected_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_bluetooth_id', sa.Binary(), nullable=False),
    sa.Column('diagnosed_or_suspected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspected_case')
    op.drop_table('device_bluetooth_id')
    # ### end Alembic commands ###
