"""added suspectedcase table

Revision ID: c0ed8fe264a4
Revises: b9cf90bc3055
Create Date: 2020-03-27 12:42:55.747266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ed8fe264a4'
down_revision = 'b9cf90bc3055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspected_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_mac_addr', sa.String(length=17), nullable=False),
    sa.Column('diagnosed_or_suspected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car_pkey')
    )
    op.drop_table('suspected_case')
    # ### end Alembic commands ###
